---
# tasks file for docker
- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
  when: ansible_os_family == "Debian"

- name: Add Docker GPG key
  get_url:
    url: https://download.docker.com/linux/{{ ansible_os_family | lower }}/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: 0644      
  when: ansible_os_family == "Debian"

- name: Add Docker repository for aaarch64 architecture
  apt_repository:
    repo: "deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_os_family | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  when: ansible_architecture == "aarch64" and ansible_os_family == "Debian"

- name: Add Docker repository for other architectures
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_os_family | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  when: ansible_architecture == "x86_64" and ansible_os_family == "Debian"

- name: Install Docker packages
  apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin 
      - docker-compose-plugin
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Create daemon.json file
  template:
    src: templates/daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: 0644

- name: Add Docker users to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop: "{{ docker_users }}"

- name: Enable and start Docker service
  systemd:
    name: docker
    enabled: yes
    state: started
